# Created with https://github.com/Hushayo/PretClient/blob/main/winget/manifests
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
PackageIdentifier: Hushayo.PretClient
PackageVersion: 2.0.14
InstallerType: inno
Scope: user
UpgradeBehavior: install
ReleaseDate: 2026-10-07
InstallModes:
- silent
- silentWithProgress
AppsAndFeaturesEntries:
- DisplayName: PretClient
  Publisher: Hushayo
  DisplayVersion: 2.0.14
  ProductCode: '{8A81D479-8604-44BF-8C72-38FB118FFEBE}_is1'
  UpgradeCode: '{8A81D479-8604-44BF-8C72-38FB118FFEBE}'
Installers:
- Architecture: x64
  Scope: user
  InstallerType: inno
  InstallerUrl: https://github.com/Hushayo/PretClient/releases/download/v2.0.14/PretClient-Setup.exe
  InstallerSha256: 483C1EABD68ECB07DC3D198B77E74A95F6C4B5199710141BF88CBF9A44C117C4
  InstallerSwitches:
    Silent: /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
    SilentWithProgress: /SILENT /SUPPRESSMSGBOXES /NORESTART /SP-
ManifestType: installer
ManifestVersion: 1.12.0
